### ISSUE TITLE
Can't get symbols.

### ISSUE THREAD

**Issue by shlomopongartz** [KVM-VMI/nitro#2]
Hi,

When in nitro/symbols.py it is written autodetect_build_local='basic',
I get the error
root@cloud-security1:/home/shlomo/nitro/KVM-VMI/kvm-vmi/nitro# ./main.py --stdout nitro_win7x64
Dumping physical memory to /tmp/tmpom2kjng2/tmp_am5tp_i
Extracting symbols with Rekall
ERROR:root:Error: HTTP Error 404: Not Found
ERROR:root:Error: HTTP Error 404: Not Found
ERROR:root:Error: HTTP Error 404: Not Found

And when it is written autodetect_build_local='none',
I get the error
root@cloud-security1:/home/shlomo/nitro/KVM-VMI/kvm-vmi/nitro# ./main.py --stdout nitro_win7x64
Dumping physical memory to /tmp/tmprkrld2di/tmpf00bkm72
Extracting symbols with Rekall
ERROR:root:No profiles match this image. Try specifying manually.

What could be the reason for that.

Best regards,

S.P.

**Comment by Wenzel** [comment]
Hi @shlomopongartz ,
one way to debug it is to uncomment this line in `symbols.py`

~~~
# logging.basicConfig(level=logging.DEBUG)
~~~
It will provide you a lot os debugging information about rekall.

Are you using the image template available in `nitro/test/packer-windows/win7x64.json` ?
I don't have any issue to ge the symbols on this one.

Apart from that, these are Rekall related errors.
You could try to open an issue on the [github tracker.](https://github.com/google/rekall/issues)

**Comment by Wenzel** [comment]
@shlomopongartz any update regarding your issue ?

**Comment by aghamir** [comment]
Hi @Wenzel ,
I've ran main.py in vagrant. I've got this error:
```
vagrant@jessie:/vagrant/nitro$ ./main.py nitro_win7x64
Finding QEMU pid for domain nitro_win7x64
Detected 1 VCPUs
Dumping physical memory to /tmp/tmp2xqs280v/tmpbhzv8j73
Extracting symbols with Rekall
Loading symbols
Traceback (most recent call last):
  File "./main.py", line 76, in <module>
    main(docopt(__doc__))
  File "./main.py", line 51, in main
    with Backend(domain, analyze_enabled) as backend:
  File "/vagrant/nitro/nitro/backend.py", line 52, in __init__
    self.libvmi = Libvmi(domain.name())
  File "/vagrant/nitro/nitro/libvmi.py", line 62, in __init__
    self.libvmi = cdll.LoadLibrary('libvmi.so')
  File "/usr/lib/python3.4/ctypes/__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libvmi.so: undefined symbol: xen_get_address_width
```
Also when I run process_list in libvmi, I get this error:
```
vagrant@jessie:/vagrant/libvmi/examples$ sudo ./vmi-process-list nitro_win7x64
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_get_address_width'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_set_vcpureg'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_init_vmi'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_write'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_get_vcpureg'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_get_vcpuregs'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_get_domainname'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_init'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_test'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_pause_vm'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_set_domainname'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_set_domainid'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_get_name_from_domainid'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_resume_vm'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_get_memsize'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_read_page'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_destroy'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_get_domainid_from_name'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_is_pv'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_set_vcpuregs'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_check_domainid'
/vagrant/libvmi/libvmi/.libs/libvmi.so: undefined reference to `xen_get_domainid'
```

**Comment by Wenzel** [comment]
hi @aghamir 

This is a different issue, not related to the symbols.
Please close this one and open a new issue with your above message.

Thanks.
